spring:
  application:
    name: picture-486-backend
  # 最大上传文件体积
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 1
        max-concurrency: 1
  profiles:
    active: dev



