spring:
  application:
    name: picture-486-backend
  #最大上传文件体积
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  profiles:
    active: dev
server:
  servlet:
    context-path: /api
    session:
      timeout: 1h


